CREATE TABLE score (
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name             VARCHAR(24) NOT NULL,
    kills            INTEGER NOT NULL,
    duration_seconds INTEGER NOT NULL,
    submitted_at     TIMESTAMP WITH TIME ZONE
);

-- Matches the top-N leaderboard query: ORDER BY kills DESC, duration_seconds ASC.
CREATE INDEX idx_score_kills_duration ON score (kills DESC, duration_seconds ASC);
